# Generated by Django 5.0.3 on 2024-03-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('respondent', models.CharField(max_length=36, unique=True)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturalness', models.SmallIntegerField()),
                ('intelligibility', models.SmallIntegerField()),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.kind')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.modelnames')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.respondents')),
                ('sample_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.samplenames')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.speaker')),
            ],
        ),
    ]
