# Generated by Django 5.0.3 on 2024-03-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='Kinds',
        ),
        migrations.RenameModel(
            old_name='Speaker',
            new_name='SpeakerNames',
        ),
        migrations.RenameField(
            model_name='respondents',
            old_name='respondent',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='speakernames',
            old_name='speaker',
            new_name='speaker_name',
        ),
    ]
