# Generated by Django 5.0.3 on 2024-03-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_kind_kinds_rename_speaker_speakernames_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='speaker',
            new_name='speaker_name',
        ),
    ]
